name: 🚀 Web - Main Branch to Production Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ main ]
  # pull_request:
  #   types:
  #     - closed
  #   branches: [ main ]

jobs:
  # if_merged:
  #   if: github.event.pull_request.merged == true
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: |
  #       echo The PR was merged
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20.11.1
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
        cache: npm

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build-nocheck

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**